/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoparqueo;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author ngonz
 */
public class ReportePorFecha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportePorFecha.class.getName());

    /**
     * Creates new form ReportePorFecha
     */
    public ReportePorFecha() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtmHoy = new javax.swing.JButton();
        LblFecha = new javax.swing.JLabel();
        BtmElegirFecha = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        BtmRegresar = new javax.swing.JButton();
        LblReporteHoy = new javax.swing.JLabel();
        LblReporteFecha = new javax.swing.JLabel();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtmHoy.setBackground(new java.awt.Color(255, 255, 255));
        BtmHoy.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        BtmHoy.setForeground(new java.awt.Color(51, 0, 0));
        BtmHoy.setText("Crear Reporte");
        BtmHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmHoyActionPerformed(evt);
            }
        });
        getContentPane().add(BtmHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, 49));

        LblFecha.setBackground(new java.awt.Color(255, 255, 255));
        LblFecha.setFont(new java.awt.Font("Edwardian Script ITC", 1, 30)); // NOI18N
        LblFecha.setForeground(new java.awt.Color(255, 255, 255));
        LblFecha.setText("Ingresar Fecha:");
        getContentPane().add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 170, 47));

        BtmElegirFecha.setBackground(new java.awt.Color(255, 255, 255));
        BtmElegirFecha.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        BtmElegirFecha.setForeground(new java.awt.Color(51, 0, 0));
        BtmElegirFecha.setText("Crear Reporte");
        BtmElegirFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmElegirFechaActionPerformed(evt);
            }
        });
        getContentPane().add(BtmElegirFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 170, 47));

        dateChooser.setBackground(new java.awt.Color(51, 0, 0));
        dateChooser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 143, 47));

        BtmRegresar.setBackground(new java.awt.Color(255, 255, 255));
        BtmRegresar.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        BtmRegresar.setForeground(new java.awt.Color(51, 0, 0));
        BtmRegresar.setText("Regresar");
        BtmRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtmRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 132, 49));

        LblReporteHoy.setBackground(new java.awt.Color(255, 255, 255));
        LblReporteHoy.setFont(new java.awt.Font("Edwardian Script ITC", 1, 30)); // NOI18N
        LblReporteHoy.setForeground(new java.awt.Color(255, 255, 255));
        LblReporteHoy.setText("Generar Reporte del Día:");
        getContentPane().add(LblReporteHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 50));

        LblReporteFecha.setBackground(new java.awt.Color(255, 255, 255));
        LblReporteFecha.setFont(new java.awt.Font("Edwardian Script ITC", 1, 30)); // NOI18N
        LblReporteFecha.setForeground(new java.awt.Color(255, 255, 255));
        LblReporteFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblReporteFecha.setText("Generar Reporte de una Fecha Diferente:");
        getContentPane().add(LblReporteFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 510, 60));

        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo5.png"))); // NOI18N
        getContentPane().add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, -6, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtmHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmHoyActionPerformed
        // TODO add your handling code here:
        Reportes cierredia = new Reportes();
        cierredia.cierrePorFecha(LocalDate.now());

    }//GEN-LAST:event_BtmHoyActionPerformed

    private void BtmElegirFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmElegirFechaActionPerformed
        // TODO add your handling code here:
        Date fecha = dateChooser.getDate();
        LocalDate fechaLD = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    Reportes reporte = new Reportes();
    reporte.cierrePorFecha(fechaLD);

    }//GEN-LAST:event_BtmElegirFechaActionPerformed

    private void BtmRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmRegresarActionPerformed
        // TODO add your handling code here:
        Interfaz regresar = new Interfaz();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtmRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportePorFecha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtmElegirFecha;
    private javax.swing.JButton BtmHoy;
    private javax.swing.JButton BtmRegresar;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblReporteFecha;
    private javax.swing.JLabel LblReporteHoy;
    private com.toedter.calendar.JDateChooser dateChooser;
    // End of variables declaration//GEN-END:variables
}
